### ISSUE TITLE
Source code for v0.9.9 not available on GitHub

### ISSUE THREAD

**Issue by mohe2015** [SergioBenitez/uncased#9]
Hi,

it seems like the source code of version https://crates.io/crates/uncased/0.9.9 and the respective commit c44154668584669e77f568752a902bfa8ae4ed7b (https://docs.rs/crate/uncased/0.9.9/source/.cargo_vcs_info.json) is not available here in the GitHub repository. Would it be possible to push the code and create a tag?

Kind regards
Moritz

**Comment by SergioBenitez** [comment]
Whoops! Thanks for letting me know.
